SET SERVEROUTPUT ON;
CREATE OR REPLACE TRIGGER STUD_TRIG AFTER INSERT ON STUDS
FOR EACH ROW
DECLARE
TOT NUMBER:=0;
BEGIN
TOT:=:NEW.S_MARK1+:NEW.S_MARK2;
INSERT INTO STUDS_MARK VALUES(:NEW.SID.TOT);
DBMS_OUTPUT.PUT_LINE('AFTER INSERT TRIGGER ACTIVATED:');

end;
/