SET SERVEROUTPUT ON;
DECLARE
CURSOR STUD_CURSOR IS SELECT * FROM STUDS;
STUD_REC STUD_CURSOR%ROWTYPE;
TOTAL NUMBER:=0;
BEGIN
OPEN STUD_CURSOR;
LOOP
FETCH STUD_CURSOR INTO STUD_REC;
EXIT WHEN STUD_CURSOR%NOTFOUND;
TOTAL:=STUD_REC.S_MARK1+STUD_REC.S_MARK2;
DBMS_OUTPUT.PUT_LINE('TOTAL MARKS OF STUDENT '||STUD_REC.S_NAME||'IS:'||TOTAL);
END LOOP;
END;
/
